export class MobilityRequest{
    NRequest:number;
    UserArea:string;
    CommissionaryStaff:string;
    DateService:string;
    TimeService:string;
    CommissionObjetive:string;
    AssignedDriver:string;
    DepartureTime:string;
    TimeArrival:string;
    KMOut:string;
    KMArrival:string;
    Entity:string;
    Distric:string;
    Address:string;
    Observation:string;
    AttachedDocument:string;
    constructor(NRequest:number,UserArea:string,CommissionaryStaff:string,DateService:string,
        TimeService:string,CommissionObjetive:string,AssignedDriver:string,DepartureTime:string,
        TimeArrival:string,KMOut:string,KMArrival:string,Entity:string,Distric:string,Address:string,
        Observation:string,AttachedDocument:string){
            this.NRequest=NRequest;
            this.UserArea=UserArea;
            this.CommissionaryStaff=CommissionaryStaff;
            this.DateService=DateService;
            this.TimeService=TimeService;
            this.CommissionObjetive=CommissionObjetive;
            this.AssignedDriver=AssignedDriver;
            this.DepartureTime=DepartureTime;
            this.TimeArrival=TimeArrival;
            this.KMOut=KMOut;
            this.KMArrival=KMArrival;
            this.Entity=Entity;
            this.Distric=Distric;
            this.Address=Address;
            this.Observation=Observation;
            this.AttachedDocument=AttachedDocument;
    }
}